### ISSUE TITLE
Blocked ?

### ISSUE THREAD

**Issue by manfye** [lthoangg/shopee-crawler#16]
Get this issue when performing request 
{'tracking_id': 'xxxx', 'action_type': 2, 'error': 90309999}

**Comment by manfye** [comment]
Get this issue when performing request
{'tracking_id': 'xxxx', 'action_type': 2, 'error': 90309999}

**Comment by rafaelribeiroo** [comment]
What did u do about it?

**Comment by fpl1116** [comment]
我在使用http请求查询订单详情时遇到
{
"0": 2,
"1": "18791ff0b3a-ec22-49db-80b4-c0973bcd44da",
"2": true,
"3": 90309999,
"5": false,
"error": 90309999
}
