### ISSUE TITLE
Could you help me by the issue?

### ISSUE THREAD

**Issue by ChiCongNguyen** [lthoangg/shopee-crawler#5]
![image](https://user-images.githubusercontent.com/36414001/132869633-ad86628b-4abe-4f62-a804-91b0bc883169.png)

**Comment by lthoangg** [comment]
This issue will be fixed soon by linked pull request.
Keep notifying me if there's any issue.

Thanks.

**Comment by lthoangg** [comment]
Anyhow, you can use the module now by installing the new version `shopee-crawler==0.1.5`

**Comment by ChiCongNguyen** [comment]
Hi it worked well for me. Just need to get it from module crawler which I could not find on your example pypi instruction page. Btw the price of product items were wrong in result, I found solution by adding value "if-none-match" to header to make better result.
Tks for your nice help

**Comment by lthoangg** [comment]
For the feature `crawl_by_shop_url`, It was a bug (that I mistakenly made when re-construct the code)
For general crawling, I found out that the price of product is correct (but 10^4 times over). So it's data engineer to transform it. lol.

Anyway, thanks again.
